// Copyright © 2025 bo6eR. All rights reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace WellGameplayTags
{
	/** Native Input Tags **/
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Native_Move);
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Native_Look);
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Native_Jump);
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Native_Run);
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Native_Optional1);
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Native_Optional2);
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Native_Optional3);
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Native_Pause);

	//~ Weapon Input Tags ~//
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Weapon_Fire);
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Weapon_Aim);
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Weapon_Reload);

	/** State Tags **/
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Jump);
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Run);
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Reload);
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Equip);

	/** Event Tags **/
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Reload);
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Equip);
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Modifier);

	/** Message Tags **/
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Attribute);
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Instance_Weapon);
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Countdown);
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Sessions_Finding);
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Modifier);
	
}
