// Copyright © 2025 bo6eR. All rights reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace WellGameplayTags
{
	/** Input Tags **/
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Jump);
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Run);

	//~ Weapon Input Tags ~//
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Weapon_Fire);
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Weapon_Aim);
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Weapon_Reload);

	/** State Tags **/
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Jump);
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Run);

	/** Event Tags **/
	WELCOMEWELLDONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_LinkLayer);
}
